blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

image:
    resource: "@AppBundle/Controller/ImageController.php"
    type:     annotation

post:
    resource: "@AppBundle/Controller/PostController.php"
    type:     annotation

cv:
    resource: "@CvBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /CV

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
