<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getLastEntity() {
        return $this->createQueryBuilder('p')->
        orderBy('p.date', 'DESC')->
        setMaxResults(1)->
        getQuery()->
        getOneOrNullResult();
    }

    public function getPostTags() {
        return $this->createQueryBuilder('p')->
        addSelect('p.tag')->
        getQuery()->
        getResult();
    }

    public function findArticleByDate() {
        return $this->createQueryBuilder('p')->
        orderBy('p.date', 'DESC')->
        getQuery()->
        getResult();
    }



    public function getDatetimeByArticle() {
        return $this->createQueryBuilder('p')->
        addSelect('p.id', 'p')->
        addSelect('p.date')->
        getQuery()->
        getResult();
    }
}
