<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastEntity() {
        return $this->createQueryBuilder('p')->
        orderBy('p.date', 'DESC')->
        setMaxResults(1)->
        getQuery()->
        getOneOrNullResult();
    }
}
